openapi: 3.0.0
info:
  title: CRM API v1.0.0
  description: "<!--\nauthorLink: 'https://github.com/novakzaballa'\nauthorName: 'Novak Zaballa'\nDate: 'Apr 16 2020'\n-->\n\n# CRM REST API code example\n\n## Author: Novak Zaballa\n\nThe scope of this sample code project is users and customers management of a CRM.\n\nThis project has been built with Serverless Framework and targeting AWS lambda with Node.js + DynamoDB. You can deploy the proyect to AWS installing and configuring serverless, or you can run the services locally, using the [serverless-offline](https://github.com/dherault/serverless-offline) plugin, which is included. The offline configuration also includes a local DynamoDB instance is provided by the [serverless-dynamodb-local](https://github.com/99xt/serverless-dynamodb-local) plugin.\n\n## Setup and test locally\n\nTo test your service locally, without having to deploy it first, you will need node.js (tested with v13.7.0) and follow the steps below in the root directory of the project.\n\n```bash\nnpm install\nserverless dynamodb install\nserverless dynamodb start --migrate\n```\n\nThe --migrate option creates the schema. Ctl+C to stop the local DynamoDB. The DB schema and data will be lost since by default the local DB is stored in memory.\n\n## Run service offline\n\nTo test the project locally use:\n\n```bash\nserverless offline start\n```\n\nAlternatively you can debug the project with VS Code. This repository includes the launch.json file needed by VS Code to run and debug this serverless project locally. How ever dynamodb needs to be started.\n\n## Configure and Deploy service to AWS\n\nFor production you will need to configure authetication the OAuth 2 provider. Replace the file oauth2_public_key.pem in the root directory with the right public signature PEM file. Also cnfigure the file secrets.json with the corresponding OAUTH_AUDIENCE value.\n\nTo deploy the service you need an account in AWS. Use the following command:\n\n```bash\nserverless deploy -v\n```  \n\n### Authorization for testing\n\nEvery request must include an authorization header containing the OAuth Bearer token. For testing purposes currently an Auth0 account is in use,  The request content type must be application/json as per the examples below. While in dev stage, I will provide valid access token of quarklap user (with only customer priveleges and not users admin permissions) via slack channel.\n\n### Live Demo\n\nYou can test locally following the former instructions, however it is also a live test  in my aws account. Change the Servers to https://mspjeecyw1.execute-api.us-east-1.amazonaws.com/dev/api in order to use it, and get a valid toket for user with email = zaballa.novak@gmail.com and password= Myt3stPass#, to start testing. Admin credentials will be provided via email or slack.\n\n"
  contact: {}
  version: '1.0'
servers:
- url: https://mspjeecyw1.execute-api.us-east-1.amazonaws.com/dev/api
  variables: {}
- url: http://localhost:3000/dev/api
  variables: {}
paths:
  /authorize:
    post:
      tags:
      - Authenticate User
      summary: Authorize example
      operationId: Authorizeexample
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizeexampleRequest'
            example:
              email: zaballa.novak@gmail.com
              password: Myt3stPass#
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
  /users/role:
    post:
      tags:
      - Users Management
      summary: setUserRole
      description: >
        ## AWS Lambda Event handler to set the role of a user in IDP (Auth0)


        handler: src/api/userHandlers/setUserRole.setUserRole

        events:
          - http:
              method: post
              path: api/users/role
              authorizer: authorizerFunc
      operationId: setUserRole
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/setUserRoleRequest'
            example:
              email: zaballa.novak@gmail.com
              role: user
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /users:
    post:
      tags:
      - Users Management
      summary: createUser
      description: >
        ## AWS Lambda Event handler to create a user in the IDP (Auth0)


        handler: src/api/userHandlers/createUser.createUser

        events:
          - http:
              method: post
              path: api/users
              authorizer: authorizerFunc
      operationId: createUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUserRequest'
            example:
              email: zaballa.novak@gmail.com
              password: Myt3stPass#
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
      - Users Management
      summary: listUsers
      description: >
        ## AWS Lambda Event handler to list users from IDP (Auth0)


        handler: src/api/userHandlers/listUsers.listUsers

        events:
          - http:
              method: get
              path: api/users
              authorizer: authorizerFunc
      operationId: listUsers
      parameters:
      - name: per_page
        in: query
        description: 'Number of users returned per page'
        required: true
        style: form
        explode: true
        schema:
          type: integer
          example: 50
      - name: page
        in: query
        description: '0 to get first page.'
        required: true
        style: form
        explode: true
        schema:
          type: integer
          example: '0'
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /customers:
    post:
      tags:
      - Customers API
      summary: putCustomer
      description: >-
        handler: src/api/customerHandlers/putCustomer.putCustomer

        events:
          - http:
              method: post
              path: api/customers
              authorizer: authorizerFunc
      operationId: putCustomer
      parameters: []
      requestBody:
        description: 'Add new customer to the CRM'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/putCustomerRequest'
            example:
              Name: Pedro Pablo
              Surname: Marmol
              Phone: (234)534543 654
              Email: pmarmol@midominio.com
              Age: 43
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
      - Customers API
      summary: listCustomers
      description: >
        ## AWS Lambda Event handler to list Customers from Database.


        handler: src/api/customerHandlers/listCustomers.listCustomers

        events:
          - http:
              method: get
              path: api/customers
              authorizer: authorizerFunc
      operationId: listCustomers
      parameters:
      - name: pageSize
        in: query
        description: 'Number of customers to be returned in every call to this endpoint.'
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 3
      - name: startKey
        in: query
        description: 'Optional, Empty or lastkey field returned by a previous call to this endpoint'
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /customers/243432324:
    get:
      tags:
      - Customers API
      summary: getCustomer
      description: >
        AWS Lambda Event handler to get one Customer from DynamoDB table.


        handler: src/api/customerHandlers/getCustomer.getCustomer

        events:
          - http:
              method: get
              path: api/customers/{id}
              authorizer: authorizerFunc
      operationId: getCustomer
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    put:
      tags:
      - Customers API
      summary: updateCustomer
      description: >
        AWS Lambda Event handler to update an existing customer in DynamoDB


        handler: src/api/customerHandlers/updateCustomer.updateCustomer

        events:
          - http:
              method: put
              path: api/customers/{id}
              authorizer: authorizerFunc
      operationId: updateCustomer
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateCustomerRequest'
            example:
              GroupId: 4
              CustomerId: 243432324
              Name: Jorge Raul
              Surname: Thousand
              Age: 52
              Email: tmorning@midominio.com
              Phone: (122)23878 343
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
  /customers/243432324/photo:
    put:
      tags:
      - Customers API
      summary: addCustomerPhoto
      description: >
        ## AWS Lambda Event handler to add a photo in S3 to an existing Customer


        handler: src/api/customerHandlers/addCustomerPhoto.addCustomerPhoto

        events:
          - http:
              method: put
              path: api/customers/{id}/photo
              authorizer: authorizerFunc
      operationId: addCustomerPhoto
      parameters: []
      requestBody:
        description: 'Base64 encoded JPG, PNG or GIF Image . Max size configured in settings.json. (150KB default)'
        content:
          text/plain:
            schema:
              type: string
              example: /9jr/4AAQSkZJRgABAgAAAQABAAD/7QCcUGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAI.....
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
      - Customers API
      summary: getCustomerPhoto
      description: >
        ## AWS Lambda Event handler to add a photo in S3 to an existing Customer


        handler: src/api/customerHandlers/getCustomerPhoto.getCustomerPhoto

        events:
          - http:
              method: get
              path: api/customers/{id}/photo
        #     authorizer: authorizerFunc
      operationId: getCustomerPhoto
      parameters:
      - name: Accept
        in: header
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: image/jpeg
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    setUserRoleRequest:
      title: setUserRoleRequest
      required:
      - email
      - role
      type: object
      properties:
        email:
          type: string
        role:
          type: string
      example:
        email: zaballa.novak@gmail.com
        role: user
    createUserRequest:
      title: createUserRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      example:
        email: zaballa.novak@gmail.com
        password: Myt3stPass#
    AuthorizeexampleRequest:
      title: AuthorizeexampleRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      example:
        email: zaballa.novak@gmail.com
        password: Myt3stPass#
    putCustomerRequest:
      title: putCustomerRequest
      required:
      - Name
      - Surname
      - Phone
      - Email
      - Age
      type: object
      properties:
        Name:
          type: string
        Surname:
          type: string
        Phone:
          type: string
        Email:
          type: string
          format: email
        Age:
          type: integer
          format: int32
          min: 16
          max: 110
      example:
        Name: Pedro Pablo
        Surname: Marmol
        Phone: (234)534543 654
        Email: pmarmol@midominio.com
        Age: 43
    updateCustomerRequest:
      title: updateCustomerRequest
      required:
      - Name
      - Surname
      - Age
      - Email
      - Phone
      type: object
      properties:
        Name:
          type: string
        Surname:
          type: string
        Phone:
          type: string
        Email:
          type: string
          format: email
        Age:
          type: integer
          format: int32
          min: 16
          max: 110
      example:
        Name: Jorge Raul
        Surname: Thousand
        Age: 52
        Email: tmorning@midominio.com
        Phone: (122)23878 343
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  
security:
- bearerAuth: []
tags:
- name: Authenticate User
- name: Users Management
- name: Customers API
